#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<math.h>

int anagaram(char arr1[],char arr2[])//user defined function to check whether strings entered in function are
{//anagram or not
    int i;
    int ch1[26]={0};//array declared to store count of alphabets of arr1 in ch1
    int ch2[26]={0};//array declared to store count of alphabets of arr2 in ch2
    while(arr1[i]!='\0')//while loop executed till string length is transvered
    {
        ch1[arr1[i]-'a']++;
        i++;
    }
    i=0;
    while(arr2[i]!='\0')//while loop executed till string length is transversed
    {
        ch2[arr2[i]-'a']++;
        i++;
    }
    for(i=0;i<26;++i)
    {
        if(ch1[i]!=ch2[i])//if count of alphabet in string is not same then strings are not anagram
            return 0;
    }
    return 1;
}

int main()//main function called
{
    int n,m=100,y;//variables declared
    printf("Enter the number of strings: ");
    scanf("%d",&n);//entering number of strings
    char **ind;//initialising pointer
    char str[n][100],s[100],s1[100];//initialising character arrays
    printf("\nEnter strings: \n");//entering strings
    ind=(char**)calloc(n,sizeof(char));//string is stored dynamically
    for(i=0;i<n;++i)
    {
        ind[i]=calloc(100,sizeof(char));
        scanf("%s",ind[i]);//string entered by user
    }
    y=(random())%n;//random number generated by system
    printf("\nEnter the value of string\n");
    scanf("%s",&s1);//string entered by user to compare
    for(i=0;i<100;++i)
        s[i]=ind[y][i];//string stored which at ind[y]
    if(anagaram(s,s1)==1)//function called and if-else statement used to obtain the final result
        printf("\nStrings %s and %s are anagram\n",s,s1);
    else
         printf("\nStrings %s and %s are not anagram\n",s,s1);
    return 0;//code finished
}
